#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '❌❌❌ Prettier Check Failed. Run npm run format, add changes and try commit again. ❌❌❌';
    false;
)

# Check ESLint Standards
npm run lint ||
(
        echo '❌❌❌ ESLint Check Failed. Make the required changes listed above, add changes and try to commit again. ❌❌❌'
        false; 
)

# If everything passes... Now we can commit
echo '🤔 Code looks good... trying build. 🤔'

npm run build ||
(
    echo '❌❌❌ build failed: View the errors above to see why ❌❌❌'
    false;
)

# If everything passes... Now we can commit
echo '✅✅ LGTM, committing now. ✅✅'